### PR TITLE
Support 2023.2

### PR DESCRIPTION
**Pull request by gaborbernat**

### CODE REVIEW

**Review by andrask — APPROVED** [review]

**Comment by andrask** [comment]
You had the maintainer role. I changed it to admin if that suits better.

**Comment by andrask** [comment]
Once the verification is complete, it should become available automatically.

**Comment by gaborbernat** [comment]
> Once the verification is complete,

When does this happen? I made some publishes yesterday and nothing shows up on Jetbrain side 🤔

**Comment by andrask** [comment]
I see two pending releases 1.3.8 and 1.3.9. Usually approved in 1-2 workdays. I invited your user to the Jetbrains org as well, I'm not sure why you don't see the releases.

**Comment by andrask** [comment]
Both releases are now available 🌟

**Pull request merged**
